######################################################################
# Automatically generated by qmake (3.0) Thu Feb 12 07:37:18 2015
######################################################################

TEMPLATE = app
TARGET = Fast5-Studio
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += mainwindow.h
SOURCES += fast5studio.cpp mainwindow.cpp
